---
version: '3.8'
services:
  # Postgres database
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: go-project-template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "6432:5432"
    networks:
      - postgres-compose-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 1

  # Redis database
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 1

networks:
  postgres-compose-network:
    driver: bridge
